server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: post-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/posts/**
          filters:
            - StripPrefix=1

        - id: media-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/media/**
          filters:
            - StripPrefix=1

        - id: search-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/search/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1

        - id: recommend-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/recommendations/**
          filters:
            - StripPrefix=1

        - id: chat-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/chat/**
          filters:
            - StripPrefix=1

        - id: video-call-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/video-calls/**
          filters:
            - StripPrefix=1

        - id: swagger-ui
          uri: http://localhost:8090
          predicates:
            - Path=/swagger/**,/swagger-ui/**,/v3/api-docs/**